### ISSUE TITLE
Old version on pip

### ISSUE THREAD

**Issue by jbma** [iconfinder/pyvat#20]
Hey,
It looks like your pip package is not updated, it's the 1.3.1 version from 2014, with the old VAT rates.
Would it be possible to update it?

**Comment by jbma** [comment]
Hi,
A small follow up, about that request 😇

**Comment by bwirtz** [comment]
+1 !

**Comment by martinleblanc** [comment]
We've updated the package a few times since this issue was created. I'll close this issue.
