### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by hegde5** [iconfinder/pyvat#22]
The latest version on `PyPI` is `1.3.1` released back in 2014. But, I see there have been several improvements since then. Are you guys planning on releasing the newest version to `PyPI?`

**Comment by gabn88** [comment]
A Pypi release would be really great!

The current PyPi release is not working on python3.7, I get this issue: https://github.com/iterative/dvc/issues/1995. It is solved in the master branch.

**Comment by carltongibson** [comment]
I think this can be closes looking at https://pypi.org/project/pyvat/#history
