### ISSUE TITLE
ebook VAT rate

### ISSUE THREAD

**Issue by gbrault** [iconfinder/pyvat#29]
[according to](https://www.globalvatcompliance.com/vat-rates-for-ebooks-2020/) ebook VAT has changed in 2019 and seems not inline with the values given by pyvat?

am-I right?

**Comment by JanmanX** [comment]
Thank you for taking the time to open this issue.

I have now fixed it and it is available in the v1.3.6 release of PyVAT!

**Comment by gbrault** [comment]
You welcome! Thanks for fixing!
