### ISSUE TITLE
Requests.post add timeout support

### ISSUE THREAD

**Issue by pymen** [iconfinder/pyvat#34]
To prevent locking if  server is not responding for some time, can you add support for `timeout` argument for requests

```
        response = requests.post(
                self.CHECK_VAT_SERVICE_URL,
                data=request_data.encode('utf-8'),
                headers={
                    'Content-Type': 'text/xml; charset=utf-8',
                }
            )
```

https://requests.readthedocs.io/en/master/user/advanced/#timeouts

for compatibility, you can set default value = None

**Comment by pymen** [comment]
timeout= self.DEFAULT_TIMEOUT

if you specify it like this, it could be changed very easy

**Comment by JanmanX** [comment]
Hi @pymen,

I have implemented a default timeout of 8 seconds, and you can expect to see a new release of the PyVAT package soon.

Thanks for you suggestion!

**Comment by pymen** [comment]
great, thanks @JanmanX, you are fast like a racer :)
