### ISSUE TITLE
Support Isle of Man and Monaco VAT numbers

### ISSUE THREAD

**Issue by kdeldycke** [iconfinder/pyvat#7]
Isle of Man (country code: `IM`) share its VAT registry with the UK. Same thing for Monaco (country code: `MC`), which is sharing its registry with France.

These exceptions are not supported by `pyvat`:

``` python
>>> from pyvat import is_vat_number_format_valid
>>> print is_vat_number_format_valid('GB 000 8920 15', 'IM')
None
>>> print is_vat_number_format_valid('FR 12 0000 4520 2', 'MC')
None
```

Here I expect `is_vat_number_format_valid()` method to return `True` in the two example above, as if the query was performed against the canonical country:

``` python
>>> print is_vat_number_format_valid('FR 12 0000 4520 2', 'FR')
True
>>> print is_vat_number_format_valid('GB 000 8920 15', 'GB')
True
```

**Comment by nickbruun** [comment]
Do you have any documentation on the VAT numbers for these two instances?

**Comment by kdeldycke** [comment]
Well, the thing is Isle of Man and UK share the same registry. Which means Isle of Man companies gets a VAT number that looks like a UK one, with a leading `GB` prefix. Same things for Monaco and France.

**Comment by nickbruun** [comment]
Okay, but, for reference, do you have any official documentation on VAT numbers in this regard?

**Comment by kdeldycke** [comment]
Can't find any summarized information on the web... I think the only way to find sources is to dig into the laws... :(

**Comment by kdeldycke** [comment]
Here is an element of proof from the official site of the French administration:
> Les entreprises enregistrées à Monaco disposent d'un numéro de TVA intracommunautaire français.
Source: http://vosdroits.service-public.fr/professionnels-entreprises/F23570.xhtml

Which roughly translates to:
> Companies registered at Monaco have a French VAT number.

**Comment by JanmanX** [comment]
I believe neither Monaco nor Isle of Man are members of the EU, and so we do not track those in the PyVAT package.
